dist: trusty
sudo: required

language: python

python:
 - "2.7"
# uncomment and edit the following line if your project needs to run something other than `rake`:

before_install:
  - sudo apt-get -qq update
  #- sudo apt-get install -y scribus
  #- sudo apt-get install -y build-essential devscripts ubuntu-dev-tools debhelper dh-make diffutils patch cdbs
  #- sudo apt-get install -y dh-python python-all python-setuptools python3-all python3-setuptools
  #- sudo apt-get install -y python-cairo python-lxml python-rsvg python-twitter
  
install: true

script:
   - python -V
 
#script:
#   - sonar-scanner
#   - sudo dpkg-buildpackage -us -uc 

#before_deploy:
#  cp ../python-selfietorium_1_all.deb python-selfietorium_1_all.deb

deploy: true
#  provider: releases
#  api_key: '$GITHUB_API_KEY'
#  file: 'python-selfietorium_1_all.deb'
#  skip_cleanup: true
#  on:
#    branch: master
#    tags: true
