sudo: required
dist: trusty
before_install:
- sudo add-apt-repository -y ppa:scribus/ppa
- sudo apt-get update -q
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
- sudo apt-get install -y xvfb
- sudo apt-get install -y scribus-ng
script:
- mkdir _build
- ls
- xvfb-run scribus -v
- xvfb-run scribus --no-gui --no-splash -py scripts/to-pdf.py inNoParticularOrder.sla
#- scribus -g -py scripts/to-pdf.py inNoParticularOrder.sla
- ls 
#- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/your_file_1.tex
#- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/your_file_2.tex
#deploy:
#  provider: releases
#  api_key:
#    secure: [YOUR KEY]
#  file:
#  - _build/your_file_1.pdf
#  - _build/your_file_2.pdf
#  skip_cleanup: true
#  on:
#    tags: true
